"""
embedded-reber --- Hochreiter & Schmidhuber, *Long Short-Term Memory*,
Neural Computation 9(8):1735-1780, 1997. Experiment 1.

The Reber grammar is a 7-symbol regular language over {B, T, P, S, X, V, E}.
The *embedded* Reber grammar wraps each Reber string in an outer
B + (T or P) + ... + (T or P) + E frame; the two outer T/P symbols must match.

The model is asked to predict the next-symbol distribution at every step.
The interesting prediction is at the second-to-last position: the outer
T/P decided 6-15 steps ago must be reproduced. Standard 1997 short-lag
LSTM benchmark.

Architecture:
    Original LSTM (Hochreiter & Schmidhuber 1997) -- input gate + output
    gate, no forget gate. 8 cells. g(z) = 4*sigma(z) - 2 input squash;
    h(z) = 2*sigma(z) - 1 cell-state squash. Linear-softmax 7-way output.

Training:
    Cross-entropy on next-symbol prediction. BPTT through full strings.
    Adam optimizer. Online (one sequence per step).

CLI:
    python3 embedded_reber.py --seed 0
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import subprocess
import sys
import time

import numpy as np


# ----------------------------------------------------------------------
# Reber grammar definition
# ----------------------------------------------------------------------

ALPHABET = ["B", "T", "P", "S", "X", "V", "E"]
SYM2IDX = {s: i for i, s in enumerate(ALPHABET)}
N_SYM = len(ALPHABET)

# Inner Reber automaton, canonical Cleeremans (1989) form. Each entry maps
# a state to a list of (emit_symbol, next_state) transitions.
INNER_REBER = {
    0: [("T", 1), ("P", 2)],          # after the inner B
    1: [("S", 1), ("X", 3)],
    2: [("T", 2), ("V", 4)],
    3: [("X", 2), ("S", 5)],
    4: [("P", 3), ("V", 5)],
    5: [("E", None)],                 # inner E -- terminal
}


def reber_legal_set(state: int) -> set[str]:
    """Set of symbols the inner automaton can emit from `state`."""
    return {sym for sym, _ in INNER_REBER[state]}


def gen_inner_reber(rng: np.random.Generator) -> str:
    """Generate one inner Reber string. Always starts with B and ends with E."""
    out = ["B"]
    state = 0
    while True:
        choices = INNER_REBER[state]
        sym, nxt = choices[rng.integers(len(choices))]
        out.append(sym)
        if nxt is None:
            break
        state = nxt
    return "".join(out)


def gen_embedded_reber(rng: np.random.Generator) -> str:
    """Generate one embedded Reber string.

    Layout: B + outer + (inner Reber) + outer + E, where outer in {T, P}
    is the same symbol both times -- the long-range dependency the LSTM
    must remember.
    """
    outer = "T" if rng.integers(2) == 0 else "P"
    inner = gen_inner_reber(rng)
    return "B" + outer + inner + outer + "E"


def legal_next(string: str, t: int) -> set[str]:
    """Return the set of symbols the embedded automaton allows AT step t+1
    given that the prefix `string[:t+1]` was generated by it.

    Used for evaluation: a prediction is "Reber-legal" iff its argmax is in
    this set. The position right before the final E forces a single
    legal symbol -- the matching outer T/P.
    """
    if t < 0 or t >= len(string) - 1:
        return set()
    pos = t + 1  # the position whose symbol we're predicting
    L = len(string)
    if pos == 1:
        return {"T", "P"}                # outer choice
    if pos == 2:
        return {"B"}                     # always B (start of inner)
    if pos == L - 1:
        return {"E"}                     # outer terminal
    if pos == L - 2:
        return {string[1]}               # MUST match outer T/P (long-range)
    # Otherwise we are inside the inner Reber. Replay the inner automaton up
    # to position `pos` (string[2] is the inner B at pos=2; inner automaton
    # state 0 is what comes immediately after the inner B).
    state = 0
    for s in string[3:pos]:
        for sym, nxt in INNER_REBER[state]:
            if sym == s and nxt is not None:
                state = nxt
                break
    return reber_legal_set(state)


# ----------------------------------------------------------------------
# Encoding
# ----------------------------------------------------------------------

def encode(string: str) -> np.ndarray:
    """One-hot encode a string of symbols. Returns (T, N_SYM)."""
    arr = np.zeros((len(string), N_SYM), dtype=np.float64)
    for t, c in enumerate(string):
        arr[t, SYM2IDX[c]] = 1.0
    return arr


def make_io(string: str) -> tuple[np.ndarray, np.ndarray]:
    """Build (X, Y) for next-symbol prediction.

    X has shape (T-1, N_SYM): the prefix symbols.
    Y has shape (T-1,) of int targets: the actual next symbol at each step.
    """
    enc = encode(string)
    return enc[:-1], np.argmax(enc[1:], axis=-1)


# ----------------------------------------------------------------------
# Original LSTM (Hochreiter & Schmidhuber 1997)
# ----------------------------------------------------------------------

def sigmoid(x: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-np.clip(x, -50.0, 50.0)))


def g_squash(z: np.ndarray) -> np.ndarray:
    """Cell-input squash: range (-2, 2)."""
    return 4.0 * sigmoid(z) - 2.0


def g_squash_grad_from_g(g: np.ndarray) -> np.ndarray:
    """d g / d z given g = g_squash(z). g = 4*sigma - 2 ⇒ sigma = (g+2)/4 ⇒
    d g / d z = 4 * sigma * (1 - sigma) = (g+2)*(2-g)/4."""
    return (g + 2.0) * (2.0 - g) / 4.0


def h_squash(s: np.ndarray) -> np.ndarray:
    """Cell-state squash: range (-1, 1)."""
    return 2.0 * sigmoid(s) - 1.0


def h_squash_grad_from_h(h: np.ndarray) -> np.ndarray:
    """d h / d s given h = h_squash(s)."""
    return (h + 1.0) * (1.0 - h) / 2.0


class LSTM1997:
    """Original LSTM with input gate + output gate, no forget gate.

    State is a single-layer block of `n_hidden` cells. Output is a linear
    softmax to N_SYM next-symbol classes.
    """

    def __init__(
        self,
        n_in: int = N_SYM,
        n_hidden: int = 8,
        n_out: int = N_SYM,
        init_scale: float = 0.2,
        rng: np.random.Generator | None = None,
    ):
        rng = rng if rng is not None else np.random.default_rng(0)
        self.n_in = n_in
        self.n_hidden = n_hidden
        self.n_out = n_out

        def init_W(rows, cols, scale=init_scale):
            return rng.standard_normal((rows, cols)) * (scale / np.sqrt(cols))

        # Concatenated input is [x, h_prev], width n_in + n_hidden.
        nx = n_in + n_hidden
        self.W_in = init_W(n_hidden, nx)
        self.W_out = init_W(n_hidden, nx)
        self.W_c = init_W(n_hidden, nx)
        self.b_in = np.full(n_hidden, -1.0)   # bias input gate negative -- gate starts closed
        self.b_out = np.full(n_hidden, -1.0)  # bias output gate negative
        self.b_c = np.zeros(n_hidden)
        self.W_y = init_W(n_out, n_hidden)
        self.b_y = np.zeros(n_out)

    # ----- params (for Adam) -------------------------------------------

    def params(self):
        return [
            self.W_in, self.W_out, self.W_c, self.b_in, self.b_out, self.b_c,
            self.W_y, self.b_y,
        ]

    def param_names(self):
        return ["W_in", "W_out", "W_c", "b_in", "b_out", "b_c", "W_y", "b_y"]

    def set_params(self, plist):
        (self.W_in, self.W_out, self.W_c, self.b_in, self.b_out, self.b_c,
         self.W_y, self.b_y) = plist

    # ----- forward + backward over one sequence ------------------------

    def forward(self, X: np.ndarray):
        """Run forward through a (T, n_in) input. Return cache for backward
        and the (T, n_out) logits."""
        T = X.shape[0]
        H = self.n_hidden
        h = np.zeros(H)
        s = np.zeros(H)

        cache = {
            "X": X, "h": np.zeros((T + 1, H)), "s": np.zeros((T + 1, H)),
            "i": np.zeros((T, H)), "o": np.zeros((T, H)),
            "g": np.zeros((T, H)), "hs": np.zeros((T, H)),
            "z": np.zeros((T, self.n_in + H)),
            "logits": np.zeros((T, self.n_out)),
        }
        cache["h"][0] = h
        cache["s"][0] = s

        for t in range(T):
            z = np.concatenate([X[t], h])
            net_in = self.W_in @ z + self.b_in
            net_out = self.W_out @ z + self.b_out
            net_c = self.W_c @ z + self.b_c
            i = sigmoid(net_in)
            o = sigmoid(net_out)
            g = g_squash(net_c)
            s = s + i * g
            hs = h_squash(s)
            h = o * hs
            logits = self.W_y @ h + self.b_y

            cache["z"][t] = z
            cache["i"][t] = i
            cache["o"][t] = o
            cache["g"][t] = g
            cache["s"][t + 1] = s
            cache["hs"][t] = hs
            cache["h"][t + 1] = h
            cache["logits"][t] = logits

        return cache

    def loss_and_grads(self, X: np.ndarray, y: np.ndarray):
        """Cross-entropy loss summed over time; gradients via BPTT.

        Returns (loss, grads_dict).
        """
        cache = self.forward(X)
        logits = cache["logits"]                              # (T, N_SYM)
        # softmax stably
        m = logits.max(axis=1, keepdims=True)
        ex = np.exp(logits - m)
        probs = ex / ex.sum(axis=1, keepdims=True)
        T = X.shape[0]
        loss = -np.log(probs[np.arange(T), y] + 1e-12).sum()

        # Output gradient
        dlogits = probs.copy()
        dlogits[np.arange(T), y] -= 1.0                       # (T, N_SYM)

        H = self.n_hidden
        dW_y = dlogits.T @ cache["h"][1:]                     # (N_SYM, H)
        db_y = dlogits.sum(axis=0)

        dW_in = np.zeros_like(self.W_in)
        dW_out = np.zeros_like(self.W_out)
        dW_c = np.zeros_like(self.W_c)
        db_in = np.zeros_like(self.b_in)
        db_out = np.zeros_like(self.b_out)
        db_c = np.zeros_like(self.b_c)

        dh_next = np.zeros(H)
        ds_next = np.zeros(H)
        for t in reversed(range(T)):
            # gradient flowing back into h_t
            dh = dlogits[t] @ self.W_y + dh_next               # (H,)
            o = cache["o"][t]
            hs = cache["hs"][t]
            i = cache["i"][t]
            g = cache["g"][t]

            # h = o * hs
            do_pre = dh * hs * o * (1.0 - o)                   # sigmoid grad
            dhs = dh * o
            ds = dhs * h_squash_grad_from_h(hs) + ds_next      # gradient on s_t

            # s_t = s_{t-1} + i * g; gradient flows additively to s_{t-1}
            di_pre = ds * g * i * (1.0 - i)                    # sigmoid grad
            dg_pre = ds * i * g_squash_grad_from_g(g)

            z = cache["z"][t]
            dW_in += np.outer(di_pre, z)
            dW_out += np.outer(do_pre, z)
            dW_c += np.outer(dg_pre, z)
            db_in += di_pre
            db_out += do_pre
            db_c += dg_pre

            # gradient onto inputs (split into x and h_{t-1})
            dz = self.W_in.T @ di_pre + self.W_out.T @ do_pre + self.W_c.T @ dg_pre
            dh_next = dz[self.n_in:]
            ds_next = ds                                        # carries through CEC

        grads = {
            "W_in": dW_in, "W_out": dW_out, "W_c": dW_c,
            "b_in": db_in, "b_out": db_out, "b_c": db_c,
            "W_y": dW_y, "b_y": db_y,
        }
        return loss, grads, cache, probs

    # ----- prediction utility ------------------------------------------

    def predict(self, X: np.ndarray) -> np.ndarray:
        cache = self.forward(X)
        logits = cache["logits"]
        m = logits.max(axis=1, keepdims=True)
        ex = np.exp(logits - m)
        return ex / ex.sum(axis=1, keepdims=True)


# ----------------------------------------------------------------------
# Adam optimizer
# ----------------------------------------------------------------------

class Adam:
    def __init__(self, params, lr=1e-2, b1=0.9, b2=0.999, eps=1e-8):
        self.lr = lr
        self.b1 = b1
        self.b2 = b2
        self.eps = eps
        self.m = [np.zeros_like(p) for p in params]
        self.v = [np.zeros_like(p) for p in params]
        self.t = 0

    def step(self, params, grads_list):
        self.t += 1
        for p, g, m, v in zip(params, grads_list, self.m, self.v):
            m[...] = self.b1 * m + (1.0 - self.b1) * g
            v[...] = self.b2 * v + (1.0 - self.b2) * (g * g)
            mh = m / (1.0 - self.b1 ** self.t)
            vh = v / (1.0 - self.b2 ** self.t)
            p -= self.lr * mh / (np.sqrt(vh) + self.eps)


# ----------------------------------------------------------------------
# Training
# ----------------------------------------------------------------------

def evaluate(net: LSTM1997, n: int = 200, rng: np.random.Generator | None = None):
    """Return (legal_acc_all_steps, outer_acc) where:

      * legal_acc_all_steps: fraction of (sequence, step) pairs whose
        argmax is one of the Reber-legal next symbols at that step
      * outer_acc: fraction of sequences where the prediction at the
        second-to-last step matches the embedded outer T/P.
    """
    rng = rng if rng is not None else np.random.default_rng(123)
    legal_hits = 0
    legal_total = 0
    outer_hits = 0
    outer_total = 0
    for _ in range(n):
        s = gen_embedded_reber(rng)
        X, _ = make_io(s)
        probs = net.predict(X)
        T = X.shape[0]
        for t in range(T):
            arg = ALPHABET[int(np.argmax(probs[t]))]
            allowed = legal_next(s, t)
            if arg in allowed:
                legal_hits += 1
            legal_total += 1
        # outer: the position that predicts s[len(s)-2] -- that's t = len(s)-3
        t_outer = len(s) - 3
        outer_arg = ALPHABET[int(np.argmax(probs[t_outer]))]
        if outer_arg == s[1]:
            outer_hits += 1
        outer_total += 1
    return legal_hits / legal_total, outer_hits / outer_total


def train(
    seed: int = 0,
    n_hidden: int = 8,
    lr: float = 1e-2,
    max_seqs: int = 8000,
    eval_every: int = 500,
    eval_n: int = 200,
    target_outer: float = 1.0,
    grad_clip: float = 5.0,
    snapshot_dir: str | None = None,
    snapshot_every: int = 0,
    verbose: bool = True,
):
    """Train an LSTM on embedded Reber. Returns dict with curves and final
    accuracies.
    """
    rng = np.random.default_rng(seed)
    net = LSTM1997(n_hidden=n_hidden, rng=rng)
    opt = Adam(net.params(), lr=lr)
    names = net.param_names()

    losses = []
    legal_curve = []
    outer_curve = []
    seq_counts = []

    snapshots = []

    eval_rng = np.random.default_rng(99999)
    for step in range(1, max_seqs + 1):
        s = gen_embedded_reber(rng)
        X, y = make_io(s)
        loss, grads, _, _ = net.loss_and_grads(X, y)
        # average per-step loss for plotting stability
        losses.append(loss / max(1, len(y)))

        # gradient clipping (global L2)
        gnorm2 = sum((grads[n] ** 2).sum() for n in names)
        gnorm = float(np.sqrt(gnorm2))
        if gnorm > grad_clip:
            scale = grad_clip / (gnorm + 1e-12)
            for n in names:
                grads[n] *= scale

        opt.step(net.params(), [grads[n] for n in names])

        if step % eval_every == 0 or step == max_seqs:
            legal_acc, outer_acc = evaluate(net, n=eval_n, rng=np.random.default_rng(99999))
            legal_curve.append(legal_acc)
            outer_curve.append(outer_acc)
            seq_counts.append(step)
            if verbose:
                print(f"  step {step:5d}  loss/step {np.mean(losses[-eval_every:]):.4f}  "
                      f"legal {legal_acc:.4f}  outer {outer_acc:.4f}")
            if outer_acc >= target_outer and legal_acc >= 0.999:
                if verbose:
                    print(f"  → solved at {step} sequences.")
                break

        if snapshot_dir and snapshot_every > 0 and step % snapshot_every == 0:
            snapshots.append({
                "step": step,
                "params": [p.copy() for p in net.params()],
            })

    return {
        "net": net,
        "losses": losses,
        "legal_curve": legal_curve,
        "outer_curve": outer_curve,
        "seq_counts": seq_counts,
        "snapshots": snapshots,
        "final_legal": legal_curve[-1] if legal_curve else 0.0,
        "final_outer": outer_curve[-1] if outer_curve else 0.0,
        "total_sequences": (seq_counts[-1] if seq_counts else 0),
    }


# ----------------------------------------------------------------------
# Environment / git utilities
# ----------------------------------------------------------------------

def git_hash() -> str:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=os.path.dirname(os.path.abspath(__file__)),
            stderr=subprocess.DEVNULL,
        )
        return out.decode().strip()
    except Exception:
        return "unknown"


def env_info() -> dict:
    return {
        "python": sys.version.split()[0],
        "numpy": np.__version__,
        "platform": platform.platform(),
        "processor": platform.processor(),
        "git": git_hash(),
    }


# ----------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--hidden", type=int, default=8)
    p.add_argument("--lr", type=float, default=1e-2)
    p.add_argument("--max-seqs", type=int, default=8000)
    p.add_argument("--eval-every", type=int, default=500)
    p.add_argument("--eval-n", type=int, default=200)
    p.add_argument("--target-outer", type=float, default=1.0)
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args()

    print(f"# embedded-reber  seed={args.seed}  hidden={args.hidden}")
    t0 = time.time()
    out = train(
        seed=args.seed,
        n_hidden=args.hidden,
        lr=args.lr,
        max_seqs=args.max_seqs,
        eval_every=args.eval_every,
        eval_n=args.eval_n,
        target_outer=args.target_outer,
        verbose=not args.quiet,
    )
    dt = time.time() - t0

    final = {
        "seed": args.seed,
        "hidden": args.hidden,
        "lr": args.lr,
        "max_seqs": args.max_seqs,
        "sequences_to_solve": out["total_sequences"],
        "final_legal_acc": out["final_legal"],
        "final_outer_acc": out["final_outer"],
        "wallclock_sec": round(dt, 2),
        "env": env_info(),
    }
    print(json.dumps(final, indent=2))


if __name__ == "__main__":
    main()
